[package]
name = "firefly-emulator"
version = "0.1.0"
edition = "2021"

[dependencies]
firefly-meta = "0.1.0"
# For accessing peripherals
firefly-device = { path = "../firefly-device" }
# For running the app
firefly-runtime = { path = "../firefly-runtime" }
# For drawing custom menus
embedded-graphics = "0.8.1"
# For showing frame buffer on the screen
embedded-graphics-simulator = "0.6.0"
directories = "5.0.1"
