[package]
name = "firefly-emulator"
version = "0.1.0"
edition = "2021"

[dependencies]
# For accessing peripherals
firefly-device = { path = "../firefly-device" }
# For running the app
firefly-runtime = { path = "../firefly-runtime" }
# For drawing custom menus
embedded-graphics = "0.8.1"
# Fo finding the VFS location
directories = "5.0.1"
# For showing frame buffer on the screen
minifb = "0.27.0"
