[package]
name = "firefly-emulator"
version = "0.13.0"
rust-version = "1.95.0"
edition = "2024"
description = "Desktop emulator for Firefly Zero"
license = "GPL-3.0"
repository = "https://github.com/firefly-zero/firefly-emulator"

[dependencies]
# parsing CLI flags
clap = { version = "4.6.6", features = ["derive"] }
# finding the VFS location
directories = "6.0.0"
# accessing peripherals
firefly-hal = "0.5.1"
# running the app
firefly-runtime = "0.13.0"
# drawing custom menus
embedded-graphics = "0.8.2"
# showing frame buffer on the screen
minifb = "0.28.0"

# [patch.crates-io]
# firefly-audio = { path = "../firefly-audio" }
# firefly-runtime = { path = "../firefly-runtime" }
# firefly-hal = { path = "../firefly-hal" }
